couture_vitrine:
    resource: "@CoutureVitrineBundle/Controller/"
    type:     annotation
    prefix:   /

couture_tailleur:
    resource: "@CoutureTailleurBundle/Controller/"
    type:     annotation
    prefix:   /atelier

couture_facturation:
    resource: "@CoutureFacturationBundle/Controller/"
    type:     annotation
    prefix:   /atelier

couture_couture:
    resource: "@CoutureCoutureBundle/Controller/"
    type:     annotation
    prefix:   /atelier

couture_client:
    resource: "@CoutureClientBundle/Controller/"
    type:     annotation
    prefix:   /atelier

  
valider_facture:
    path: /{id}/valider-facture/{destination}
    defaults: { _controller:CoutureFacturationBundle:Facture:valider }

regler_facture:
    path: /{id}/regler-facture/{destination}
    defaults: { _controller:CoutureFacturationBundle:Facture:regler }

cloturer_couture:
    path: /{id}/cloturer-couture/{destination}
    defaults: { _controller:CoutureCoutureBundle:Couture:cloturer }    
    
liste_coutures:
    path: /{id}/liste-coutures
    defaults: { _controller:CoutureClientBundle:Client:listeCoutures }

liste_factures:
    path: /{id}/liste-factures
    defaults: { _controller:CoutureClientBundle:Client:listeFactures }
# app/config/routing.yml
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

app:
    resource: @AppBundle/Controller/
    type:     annotation
    

vitrineIndex:
    path: /
    defaults: { _controller:CoutureCoutureBundle:Modele:vitrine }
    
licence:
    path: /licence
    defaults: { _controller:CoutureVitrineBundle:Vitrine:licence }
    

a_propos:
    path: /a-propos
    defaults: { _controller:CoutureVitrineBundle:Vitrine:apropos }



    
dashboard:
    path: /dashboard
    defaults: { _controller:CoutureTailleurBundle:Tailleur:dashboard }
    
connexion:
    path: /connexion
    defaults: { _controller:CoutureTailleurBundle:Tailleur:dashboard }
    

#routing.yml
#SonataAdminBundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
#routing.yml
#SonataUserBundle
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
    
    
