couture_tailleur:
    resource: "@CoutureTailleurBundle/Controller/"
    type:     annotation
    prefix:   /atelier

couture_facturation:
    resource: "@CoutureFacturationBundle/Controller/"
    type:     annotation
    prefix:   /atelier

couture_couture:
    resource: "@CoutureCoutureBundle/Controller/"
    type:     annotation
    prefix:   /atelier

couture_client:
    resource: "@CoutureClientBundle/Controller/"
    type:     annotation
    prefix:   /atelier
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



app:
    resource: @AppBundle/Controller/
    type:     annotation
    

dashboard:
    path: /dashboard
    defaults: { _controller:CoutureTailleurBundle:Tailleur:dashboard }
    
connexion:
    path: /connexion
    defaults: { _controller:CoutureTailleurBundle:Tailleur:dashboard }
    
    
    
