Facture:
    type: entity
    table: facture
    indexes:
        fk_facture_couture1_idx:
            columns:
                - couture
        fk_facture_etatfacture1_idx:
            columns:
                - etatfacture
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: true
        datemod:
            type: datetime
            nullable: true
        datec:
            type: datetime
            nullable: true
        iduser:
            type: integer
            nullable: true
            unsigned: false
            column: idUser
        avance:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
    manyToOne:
        couture:
            targetEntity: Couture
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                couture:
                    referencedColumnName: id
            orphanRemoval: false
        etatfacture:
            targetEntity: Etatfacture
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                etatfacture:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
