Tache:
    type: entity
    table: tache
    indexes:
        fk_tache_spiderman1_idx:
            columns:
                - idspiderman
        fk_tache_tailleur1_idx:
            columns:
                - idTailleur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        intervention:
            type: string
            nullable: true
            length: 255
            fixed: false
        frais:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        etat:
            type: integer
            nullable: true
            unsigned: false
        datec:
            type: datetime
            nullable: true
        datemod:
            type: datetime
            nullable: true
        iduser:
            type: integer
            nullable: true
            unsigned: false
            column: idUser
    manyToOne:
        idspiderman:
            targetEntity: Couture
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idspiderman:
                    referencedColumnName: id
            orphanRemoval: false
        idtailleur:
            targetEntity: Tailleur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idTailleur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
